
BANK = [
    # -----APPETIZERS-----
    {
        'food_category': 'Appetizers',
        'food': 'BBQ Wings',
        'price': 15.00,
        'quantity': 0,
    },
    {
        'food_category': 'Appetizers',
        'food': 'Soup',
        'price': 5.00,
        'quantity': 0,
    },
    {
        'food_category': 'Appetizers',
        'food': 'Unlimited Bread',
        'price': 8.00,
        'quantity': 0,
    },
    {
        'food_category': 'Appetizers',
        'food': 'Onion Rings',
        'price': 6.00,
        'quantity': 0,
    },
    {
        'food_category': 'Appetizers',
        'food': 'Limited Bread',
        'price': 4.00,
        'quantity': 0,
    },
    {
        'food_category': 'Appetizers',
        'food': 'Cocktail Shrimp',
        'price': 11.00,
        'quantity': 0,
    },
    {
        'food_category': 'Appetizers',
        'food': 'Spiced Lemon',
        'price': 14.00,
        'quantity': 0,
    },
    {
        'food_category': 'Appetizers',
        'food': 'Cornbread',
        'price': 5.00,
        'quantity': 0,
    },
    {
        'food_category': 'Appetizers',
        'food': 'Meat Bun',
        'price': 3.00,
        'quantity': 0,
    },
    # -----ENTREES-----
    {
        'food_category': 'Entrees',
        'food': 'Peking Duck',
        'price': 33.00,
        'quantity': 0,
    },
    {
        'food_category': 'Entrees',
        'food': 'Sweet and Sour Pork',
        'price': 13.00,
        'quantity': 0,
    },
    {
        'food_category': 'Entrees',
        'food': 'Baked Vegetable Platter',
        'price': 8.00,
        'quantity': 0,
    },
    {
        'food_category': 'Entrees',
        'food': 'Sushi',
        'price': 11.00,
        'quantity': 0,
    },
    {
        'food_category': 'Entrees',
        'food': 'Grilled Salmon',
        'price': 18.00,
        'quantity': 0,
    },
    {
        'food_category': 'Entrees',
        'food': 'Chicken Parmesean',
        'price': 14.00,
        'quantity': 0,
    },
    {
        'food_category': 'Entrees',
        'food': 'Avocado Toast',
        'price': 2.00,
        'quantity': 0,
    },
    {
        'food_category': 'Entrees',
        'food': 'Turducken',
        'price': 32.00,
        'quantity': 0,
    },
    {
        'food_category': 'Entrees',
        'food': 'Monster Steak',
        'price': 48.00,
        'quantity': 0,
    },
    # -----SIDES-----
    {
        'food_category': 'Sides',
        'food': 'French Fries',
        'price': 4.00,
        'quantity': 0,
    },
    {
        'food_category': 'Sides',
        'food': 'Mashed Potatoes',
        'price': 5.00,
        'quantity': 0,
    },
    {
        'food_category': 'Sides',
        'food': 'Hash Browns',
        'price': 3.00,
        'quantity': 0,
    },
    {
        'food_category': 'Sides',
        'food': 'Baked Potato',
        'price': 3.00,
        'quantity': 0,
    },
    {
        'food_category': 'Sides',
        'food': 'Latkes',
        'price': 7.00,
        'quantity': 0,
    },
    {
        'food_category': 'Sides',
        'food': 'Potatoes Au Gratin',
        'price': 7.00,
        'quantity': 0,
    },
    {
        'food_category': 'Sides',
        'food': 'Deluxe Condiments',
        'price': 2.00,
        'quantity': 0,
    },
    {
        'food_category': 'Sides',
        'food': 'Spinach',
        'price': 2.00,
        'quantity': 0,
    },
    {
        'food_category': 'Sides',
        'food': 'Vegetable Bun',
        'price': 7.00,
        'quantity': 0,
    },
    # -----DESSERTS-----
    {
        'food_category': 'Desserts',
        'food': 'Hot Fudge Sundae',
        'price': 6.00,
        'quantity': 0,
    },
    {
        'food_category': 'Desserts',
        'food': 'Pancakes',
        'price': 5.00,
        'quantity': 0,
    },
    {
        'food_category': 'Desserts',
        'food': 'Cookies and Milk',
        'price': 4.00,
        'quantity': 0,
    },
    {
        'food_category': 'Desserts',
        'food': 'Fluffernutter Sandwich',
        'price': 3.00,
        'quantity': 0,
    },
    {
        'food_category': 'Desserts',
        'food': 'Ice Cream Moci',
        'price': 8.00,
        'quantity': 0,
    },
    {
        'food_category': 'Desserts',
        'food': 'Bananas Foster',
        'price': 10.00,
        'quantity': 0,
    },
    {
        'food_category': 'Desserts',
        'food': 'Banana Split',
        'price': 7.00,
        'quantity': 0,
    },
    {
        'food_category': 'Desserts',
        'food': 'Stolen Candy',
        'price': 1.00,
        'quantity': 0,
    },
    {
        'food_category': 'Desserts',
        'food': 'Cookie Bun',
        'price': 9.00,
        'quantity': 0,
    },
    # -----BEVERAGES-----
    {
        'food_category': 'Beverages',
        'food': 'Coffee',
        'price': 2.00,
        'quantity': 0,
    },
    {
        'food_category': 'Beverages',
        'food': 'Bubble Tea',
        'price': 4.00,
        'quantity': 0,
    },
    {
        'food_category': 'Beverages',
        'food': 'Cola',
        'price': 2.00,
        'quantity': 0,
    },
    {
        'food_category': 'Beverages',
        'food': 'Iced Tea',
        'price': 2.00,
        'quantity': 0,
    },
    {
        'food_category': 'Beverages',
        'food': 'Green Tea',
        'price': 2.00,
        'quantity': 0,
    },
    {
        'food_category': 'Beverages',
        'food': 'Pumpkin Spice Milkshake',
        'price': 40.00,
        'quantity': 0,
    },
    {
        'food_category': 'Beverages',
        'food': 'Ninja Water',
        'price': 6.00,
        'quantity': 0,
    },
    {
        'food_category': 'Beverages',
        'food': 'Better Coffee',
        'price': 3.00,
        'quantity': 0,
    },
    {
        'food_category': 'Beverages',
        'food': 'Runny Yogurt',
        'price': 5.00,
        'quantity': 0,
    },
]
